#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bank
#    username: root
#    password: raju123
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true